#!/bin/env python3


from os import path
from random import randint
import argparse





def parseArgs():
	global args

	argparser = argparse.ArgumentParser(description="Damages a file by writing random bytes at random positions to it.", epilog="Written by David Losantos")
	argparser.add_argument("file", help="File to open")
	argparser.add_argument("-p", "--passes", help="Quantity of bytes to modify. Default is 15", type=int, default=15)
	argparser.add_argument("-o", "--output", help="File to output the generated bytes to", default=None)
	argparser.add_argument("-s", "--string", help="Take the string specified for the filename as input", action="store_true")
	argparser.add_argument("-q", "--quiet", help="Do not output any text to stdout", action="store_true")

	args = argparser.parse_args()

	if not path.isfile(args.file):
		if not args.string:
			print(f"The file '{args.file}' does not exist.")
			quit()






def main():
	byteLst = []

	if args.string:
		for char in args.file:
			byteLst.append(str.encode(char))
	else:
		with open(args.file, "rb") as f:
			# Iterate over every byte and append it to a bytelist
			byte = f.read(1)
			while byte:
				byteLst.append(byte)
				byte = f.read(1)


	# Replace a random byte on the array with a random value on every pass
	for x in range(0, args.passes):
		rnd = bytes([randint(0, 255)])
		index = randint(0, len(byteLst)) - 1

		byteLst.pop(index)
		byteLst.insert(index, rnd)


	if not args.quiet:
		for byte in byteLst:
			print(str(byte.decode("utf-8", "replace")), end="")
		print()

	if args.output:
		with open(args.output, "wb") as out:
			for byte in byteLst:
				out.write(byte)







if __name__ == "__main__":
	parseArgs()
	main()